apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - franslourens.co.za
        - www.franslourens.co.za
        - staging.franslourens.co.za
        - testing.franslourens.co.za
      secretName: letsencrypt-prod
  rules:
    - host: franslourens.co.za
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress-cluster-ip-service
              servicePort: 80
    - host: www.franslourens.co.za
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress-cluster-ip-service
              servicePort: 80
    - host: staging.franslourens.co.za
      http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 80
    - host: testing.franslourens.co.za
      http:
        paths:
          - path: /
            backend:
              serviceName: phpmyadmin-cluster-ip-service
              servicePort: 80